### ISSUE TITLE
content search: uncaught error when publisher has no content access

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-python#222]
When performing any `rsconnect content search` command with a Publisher who has no access to content we hit an uncaught error.

Expected:
Return an empty json object:
`> rsconnect content search --published -s http://54.172.111.193:3939/ -k OGZMyP8jevQB3Bp9I17IhMR6VZ2TnHQP-v`
```
[]
```

Actual:
The command errors:

`> rsconnect content search --published -s http://54.172.111.193:3939/ -k OGZMyP8jevQB3Bp9I17IhMR6VZ2TnHQP-v`
```
[DEBUG] 2022-02-09T11:43:28-0500 Request: GET /__api__/v1/content
[DEBUG] 2022-02-09T11:43:28-0500 Headers:
[DEBUG] 2022-02-09T11:43:28-0500 --> User-Agent: rsconnect-python/1.7.0b4
[DEBUG] 2022-02-09T11:43:28-0500 --> Cookie: rscid=MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea; rscid-legacy=MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea
[DEBUG] 2022-02-09T11:43:28-0500 --> Authorization: Key OGZMyP8jevQB3Bp9I17IhMR6VZ2TnHQP
[DEBUG] 2022-02-09T11:43:28-0500 Response: 200 OK
[DEBUG] 2022-02-09T11:43:28-0500 Headers:
[DEBUG] 2022-02-09T11:43:28-0500 --> Cache-Control: no-cache, no-store, must-revalidate
[DEBUG] 2022-02-09T11:43:28-0500 --> Content-Type: application/json; charset=utf-8
[DEBUG] 2022-02-09T11:43:28-0500 --> Expires: 0
[DEBUG] 2022-02-09T11:43:28-0500 --> Pragma: no-cache
[DEBUG] 2022-02-09T11:43:28-0500 --> Server: RStudio Connect v2022.01.0-dev+881
[DEBUG] 2022-02-09T11:43:28-0500 --> X-Content-Type-Options: nosniff
[DEBUG] 2022-02-09T11:43:28-0500 --> X-Correlation-Id: 8d013950-d8d4-4562-a619-786f21a8e27c
[DEBUG] 2022-02-09T11:43:28-0500 --> X-Frame-Options: DENY
[DEBUG] 2022-02-09T11:43:28-0500 --> Date: Wed, 09 Feb 2022 16:43:28 GMT
[DEBUG] 2022-02-09T11:43:28-0500 --> Content-Length: 2
[DEBUG] 2022-02-09T11:43:28-0500 --> []
[DEBUG] 2022-02-09T11:43:28-0500 CookieJar contents: ['rscid', 'rscid-legacy']
{'rscid': 'MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea', 'rscid-legacy': 'MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea'}
[DEBUG] 2022-02-09T11:43:28-0500 Cookie: rscid=MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea; rscid-legacy=MTY0NDQyNTAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRdXhWbThoanFUeC1WVUFPdWV3c2JtQVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpFQjk1Z0JuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NUUgzbUE9fIVu0rob386g49FDKN8mAFa_8Uz3Sh7WzA6U9aXqQoea
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/actions.py", line 74, in cli_feedback
    yield
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/main.py", line 1413, in content_search
    result = search_content(connect_server, published, unpublished, content_type, r_version, py_version, title_contains, order_by)
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/actions_content.py", line 314, in search_content
    result = _apply_content_filters(result, published, unpublished, content_type, r_version, py_version, title_contains)
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/actions_content.py", line 357, in _apply_content_filters
    result = iter(content_list)
TypeError: 'HTTPResponse' object is not iterable
Internal error: 'HTTPResponse' object is not iterable
```

If I add that same Publisher to a piece of content, we successfully return that content:
`> rsconnect content search --published -s http://54.172.111.193:3939/ -k OGZMyP8jevQB3Bp9I17IhMR6VZ2TnHQP-v`

```
[
  {
    "guid": "14f591ef-2aad-41de-8899-d5ba71c19f33",
    "name": "portfolio_dashboard",
    "title": "Portfolio Dashboard",
    "description": "",
    "access_type": "acl",
    "connection_timeout": null,
    "read_timeout": null,
    "init_timeout": null,
    "idle_timeout": null,
    "max_processes": null,
    "min_processes": null,
    "max_conns_per_process": null,
    "load_factor": null,
    "created_time": "2022-02-09T15:58:07Z",
    "last_deployed_time": "2022-02-09T15:58:07Z",
    "bundle_id": "8",
    "app_mode": "shiny",
    "content_category": "",
    "parameterized": false,
    "cluster_name": "Local",
    "image_name": null,
    "r_version": "3.6.3",
    "py_version": null,
    "quarto_version": null,
    "run_as": null,
    "run_as_current_user": false,
    "owner_guid": "89a34fd6-2e38-4666-824e-741a80cf2728",
    "content_url": "http://54.172.111.193:3939/content/14f591ef-2aad-41de-8899-d5ba71c19f33/",
    "dashboard_url": "http://54.172.111.193:3939/connect/#/apps/14f591ef-2aad-41de-8899-d5ba71c19f33",
    "app_role": "viewer",
    "id": "8"
  }
]
```

**Comment by kgartland-rstudio** [comment]
This error also occurs when a publisher tries to `rsconnect content build add` a piece of content they don't own.

```
> rsconnect content build add -g 1b42dc18-8702-4e60-b496-090af5550705 -g 7257c8e8-7252-4420-bd1e-0578f25091ad -g 18352b75-57d0-4667-8c02-ccb638614d48 -s http://54.236.11.252:3939/ -k Ha24YQkPRokvLk1dFjadco6iJ4oAyDK6
[INFO] 2022-02-09T16:03:04-0500 Initializing ContentBuildStore for http://54.236.11.252:3939/
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/actions.py", line 74, in cli_feedback
    yield
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/main.py", line 1583, in add_content_build
    build_add_content(connect_server, guid)
  File "/Users/kgartland/.pyenv/versions/3.8.2/envs/rsconnect-tag/lib/python3.8/site-packages/rsconnect/actions_content.py", line 52, in build_add_content
    content_to_add = list(filter(lambda x: x['guid'] in guids_to_add, all_content))
TypeError: 'HTTPResponse' object is not iterable
Internal error: 'HTTPResponse' object is not iterable
```
