### ISSUE TITLE
rsconnect list errors when no api-key included

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-python#283]
As of `rsconnect-python` 1.10.0, the `api-key` is no longer required when adding a new server.  However after adding a server with a missing api-key we return an error when running `rsconnect list`:

```
> rsconnect list
Server information from /Users/kgartland/Library/Application Support/rsconnect-python/servers.json

Nickname: "fuzz"
    URL: http://18.232.160.200:3939/
    API key is saved
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rsconnect/actions.py", line 80, in cli_feedback
    yield
  File "/Users/kgartland/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rsconnect/main.py", line 389, in list_servers
    if server["insecure"]:
KeyError: 'insecure'
```

We also display "API key is saved" when there is no API Key.

The servers.json file contains:

```
{
    "fuzz": {
        "name": "fuzz",
        "url": "http://18.232.160.200:3939/",
        "account_name": null,
        "token": null,
        "secret": null
    }
}
```

After adding an api_key to the config, the servers.json file looks like this:

```
{
    "fuzz": {
        "name": "fuzz",
        "url": "http://18.232.160.200:3939/",
        "api_key": "[REDACTED]",
        "insecure": false,
        "ca_cert": null
    }
}
```

I think if there is no `-k` provided, we default to shinyapps.io credential structure.

**Comment by kgartland-rstudio** [comment]
should we update our `--help` menus?  we currently only state RStudio Connect as the deploy target:

`-> rsconnect deploy --help`

> Usage: rsconnect deploy [OPTIONS] COMMAND [ARGS]...
> 
>   Deploy content to RStudio Connect.
> 
> Options:
>   --help  Show this message and exit.
> 
> Commands:
>   api            Deploy a Python API to RStudio Connect [v1.8.2+].
>   bokeh          Deploy a Bokeh Application to RStudio Connect [v1.8.4+].
>   dash           Deploy a Dash Application to RStudio Connect [v1.8.2+].
>   fastapi        Deploy a Python FastAPI to RStudio Connect [v2021.08.0+].
>   html           Deploy html content to RStudio Connect.
>   manifest       Deploy content to RStudio Connect by manifest.
>   notebook       Deploy Jupyter notebook to RStudio Connect [v1.7.0+].
>   other-content  Describe deploying other content to RStudio Connect.
>   quarto         Deploy Quarto content to RStudio Connect [v2021.08.0+].
>   shiny          Deploy a Python Shiny Application to RStudio Connect
>                  [v2022.07.0+].
>   streamlit      Deploy a Streamlit Application to RStudio Connect [v1.8.4+].


`-> rsconnect --help`

> Usage: rsconnect [OPTIONS] COMMAND [ARGS]...
> 
>   This command line tool may be used to deploy Jupyter notebooks to RStudio
>   Connect.  Support for deploying other content types is also provided.
> 
>   The tool supports the notion of a simple nickname that represents the
>   information needed to interact with an RStudio Connect server instance.  Use
>   the add, list and remove commands to manage these nicknames.
> 
>   The information about an instance of RStudio Connect includes its URL, the
>   API key needed to authenticate against that instance, a flag that notes
>   whether TLS certificate/host verification should be disabled and a path to a
>   trusted CA certificate file to use for TLS.  The last two items are only
>   relevant if the URL specifies the "https" protocol.
> 
> Options:
>   --help  Show this message and exit.
> 
> Commands:
>   add             Define a nickname for an RStudio Connect or shinyapps.io
>                   server and credential.
>   content         Interact with RStudio Connect's content API.
>   deploy          Deploy content to RStudio Connect.
>   details         Show details about an RStudio Connect server.
>   info            Show saved information about the specified deployment.
>   list            List the known RStudio Connect servers.
>   remove          Remove the information about an RStudio Connect server.
>   version         Show the version of the rsconnect-python package.
>   write-manifest  Create a manifest.json file for later deployment.


`-> rsconnect deploy shiny --help`

> Usage: rsconnect deploy shiny [OPTIONS] DIRECTORY [EXTRA_FILES]...
> 
>   Deploy a Python Shiny Application module to RStudio Connect. The "directory"
>   argument must refer to an existing directory that contains the application
>   code.
> 
> Options:
>   -n, --name TEXT         The nickname of the RStudio Connect server to deploy
>                           to.
>   -s, --server TEXT       The URL for the RStudio Connect server to deploy to.
>   -k, --api-key TEXT      The API key to use to authenticate with RStudio
>                           Connect.
>   -i, --insecure          Disable TLS certification/host validation.
>   -c, --cacert FILENAME   The path to trusted TLS CA certificates.
>   -v, --verbose           Print detailed messages.
>   -N, --new               Force a new deployment, even if there is saved
>                           metadata from a previous deployment. Cannot be used
>                           with --app-id.
>   -a, --app-id TEXT       Existing app ID or GUID to replace. Cannot be used
>                           with --new.
>   -t, --title TEXT        Title of the content (default is the same as the
>                           filename).
>   -E, --environment TEXT  Set an environment variable. Specify a value with
>                           NAME=VALUE, or just NAME to use the value from the
>                           local environment. May be specified multiple times.
>                           [v1.8.6+]
>   -A, --account TEXT      The shinyapps.io/RStudio Cloud account name.
>   -T, --token TEXT        The shinyapps.io/RStudio Cloud token.
>   -S, --secret TEXT       The shinyapps.io/RStudio Cloud token secret.
>   -e, --entrypoint TEXT   The module and executable object which serves as the
>                           entry point for the Python Shiny Application
>                           (defaults to app)
>   -x, --exclude TEXT      Specify a glob pattern for ignoring files when
>                           building the bundle. Note that your shell may try to
>                           expand this which will not do what you expect.
>                           Generally, it's safest to quote the pattern. This
>                           option may be repeated.
>   -p, --python PATH       Path to Python interpreter whose environment should
>                           be used. The Python environment must have the
>                           rsconnect package installed.
>   -g, --force-generate    Force generating "requirements.txt", even if it
>                           already exists.
>   -I, --image TEXT        Target image to be used during content execution
>                           (only applicable if the RStudio Connect server is
>                           configured to use off-host execution)
>   --help                  Show this message and exit.

`-> rsconnect add --help`

> Usage: rsconnect add [OPTIONS]
> 
>   Associate a simple nickname with the information needed to interact with an
>   RStudio Connect server. Specifying an existing nickname will cause its
>   stored information to be replaced by what is given on the command line.
> 
> Options:
>   -n, --name TEXT        The nickname of the RStudio Connect server to deploy
>                          to.  [required]
>   -s, --server TEXT      The URL for the RStudio Connect server to deploy to.
>   -k, --api-key TEXT     The API key to use to authenticate with RStudio
>                          Connect.
>   -i, --insecure         Disable TLS certification/host validation.
>   -c, --cacert FILENAME  The path to trusted TLS CA certificates.
>   -A, --account TEXT     The shinyapps.io/RStudio Cloud account name.
>   -T, --token TEXT       The shinyapps.io/RStudio Cloud token.
>   -S, --secret TEXT      The shinyapps.io/RStudio Cloud token secret.
>   -v, --verbose          Print detailed messages.
>   --help                 Show this message and exit.
